# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import popoteafrica.models


class Migration(migrations.Migration):

    dependencies = [
        ('popoteafrica', '0002_auto_20160912_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesafaricollection',
            name='price',
            field=models.IntegerField(default=b'1000', help_text=b'Fill in the price for this trip'),
        ),
        migrations.AddField(
            model_name='thesafaricollection',
            name='trip_duration',
            field=models.IntegerField(default=0, help_text=b'Fill in How many days the trip would take'),
        ),
        migrations.AddField(
            model_name='thesafaricollection',
            name='trip_name',
            field=models.CharField(default=b'fill in about Trip Name', max_length=1000),
        ),
        migrations.AddField(
            model_name='thesafaricollection',
            name='trip_route',
            field=models.ForeignKey(help_text=b'Put a Mountain Safari Trips Only', null=True, on_delete=django.db.models.deletion.CASCADE, to='popoteafrica.Route'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_1_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_2_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_3_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_4_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_5_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_6_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_7_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_8_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_9_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='thesafaricollection',
            name='depature_dates',
            field=models.DateField(help_text=b'The day trip will start'),
        ),
        migrations.AlterField(
            model_name='thesafaricollection',
            name='return_dates',
            field=models.DateField(help_text=b'The day trip will end'),
        ),
    ]
