# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import popoteafrica.models


class Migration(migrations.Migration):

    dependencies = [
        ('popoteafrica', '0014_auto_20160914_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMountainTripsForOpenDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depature_date', models.DateField(help_text=b'Put a the date that the trip is departing')),
                ('return_date', models.DateField(help_text=b'Put a the date that the trip is returning')),
                ('price', models.IntegerField(help_text=b'Put a the price of this trip')),
                ('trip_duration', models.IntegerField(default=0, help_text=b'Put a the number of days that will be spent in this trip')),
                ('about_trip', models.CharField(default=b'fill in about Trip', max_length=10000)),
                ('trip_name', models.CharField(default=b'fill in about Trip Name', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='allmountaintrips',
            name='trip_route',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.AlterField(
            model_name='aboutguides',
            name='about_guides_body',
            field=models.CharField(help_text=b'Put The contents here', max_length=10000),
        ),
        migrations.AlterField(
            model_name='aboutguides',
            name='head',
            field=models.CharField(help_text=b'Put The Heading/ name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_1_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_2_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_3_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_4_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_5_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_6_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_7_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_8_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_9_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='allonedayprogramtrips',
            name='depature_date',
            field=models.DateField(help_text=b'Put a the date that the trip is departing'),
        ),
        migrations.AlterField(
            model_name='allonedayprogramtrips',
            name='price',
            field=models.IntegerField(help_text=b'Put a the price of this trip'),
        ),
        migrations.AlterField(
            model_name='allonedayprogramtrips',
            name='return_date',
            field=models.DateField(help_text=b'Put a the date that the trip is returning'),
        ),
        migrations.AlterField(
            model_name='allonedayprogramtrips',
            name='trip_duration',
            field=models.IntegerField(default=0, help_text=b'Put a the number of days that will be spent in this trip'),
        ),
        migrations.AlterField(
            model_name='allonedayprogramtrips',
            name='trip_route',
            field=models.ForeignKey(help_text=b'Put a One Day Program Trip Only', null=True, on_delete=django.db.models.deletion.CASCADE, to='popoteafrica.Route'),
        ),
        migrations.AlterField(
            model_name='allzanzibartrips',
            name='depature_date',
            field=models.DateField(help_text=b'Put a the date that the trip is departing'),
        ),
        migrations.AlterField(
            model_name='allzanzibartrips',
            name='price',
            field=models.IntegerField(help_text=b'Put a the price of this trip'),
        ),
        migrations.AlterField(
            model_name='allzanzibartrips',
            name='return_date',
            field=models.DateField(help_text=b'Put a the date that the trip is returning'),
        ),
        migrations.AlterField(
            model_name='allzanzibartrips',
            name='trip_duration',
            field=models.IntegerField(default=0, help_text=b'Put a the number of days that will be spent in this trip'),
        ),
        migrations.AlterField(
            model_name='allzanzibartrips',
            name='trip_route',
            field=models.ForeignKey(help_text=b'Put a Zanzibar Trip Only', null=True, on_delete=django.db.models.deletion.CASCADE, to='popoteafrica.Route'),
        ),
        migrations.AlterField(
            model_name='animalmigrations',
            name='body_contents',
            field=models.CharField(help_text=b'put the contents of the heading here', max_length=10000),
        ),
        migrations.AlterField(
            model_name='animalmigrations',
            name='head',
            field=models.CharField(help_text=b'put the heading here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='animalmigrations',
            name='subtitle',
            field=models.CharField(blank=True, help_text=b'put a subheading if available or leave blank', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsmountainopendates',
            name='trip_booked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popoteafrica.AllMountainTripsForOpenDates'),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents2',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents3',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents4',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents5',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents6',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents7',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents8',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='body_contents9',
            field=models.CharField(blank=True, help_text=b'put contents of the heading here or leave blank', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='climbkilimanjarotips',
            name='head',
            field=models.CharField(blank=True, help_text=b'put the heading here', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_body',
            field=models.CharField(help_text=b'put contents of the heading here', max_length=10000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='head',
            field=models.CharField(help_text=b'put the heading here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='howtoplanasafari',
            name='body_contents',
            field=models.CharField(help_text=b'put contents of the heading here', max_length=10000),
        ),
        migrations.AlterField(
            model_name='howtoplanasafari',
            name='head',
            field=models.CharField(help_text=b'put the heading here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item1',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item10',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item11',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item12',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item13',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item14',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item15',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item2',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item3',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item4',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item5',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item6',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item7',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item8',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='item9',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kilipacklist',
            name='list_heading',
            field=models.CharField(blank=True, help_text=b'Put the heading of the list', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='about_route',
            field=models.CharField(help_text=b'Put The contents of the Route or the page', max_length=10000),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(help_text=b'Put The Heading/ name of the Route or the page', max_length=1000),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item1',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item10',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item11',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item12',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item13',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item14',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item15',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item2',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item3',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item4',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item5',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item6',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item7',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item8',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='item9',
            field=models.CharField(blank=True, help_text=b'mention an item here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safaripacklist',
            name='list_heading',
            field=models.CharField(blank=True, help_text=b'put the name of tis list', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='head',
            field=models.CharField(help_text=b'Put The Heading/ name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_body',
            field=models.CharField(help_text=b'Put The contents here', max_length=10000),
        ),
        migrations.DeleteModel(
            name='AllMountainTrips',
        ),
        migrations.AddField(
            model_name='allmountaintripsforopendates',
            name='trip_route',
            field=models.ForeignKey(help_text=b'Put a Mountain Route Only', null=True, on_delete=django.db.models.deletion.CASCADE, to='popoteafrica.Route'),
        ),
    ]
