# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import popoteafrica.models


class Migration(migrations.Migration):

    dependencies = [
        ('popoteafrica', '0017_auto_20160915_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariPlansForTheChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_days', models.IntegerField(default=0, help_text=b'Put The number of days for this plan')),
                ('trip_price', models.IntegerField(blank=True, default=1000, help_text=b'Put The price for this plan', null=True)),
                ('days_arusha_park', models.CharField(default=0, help_text=b'Put The number of days at arusha national park for this plan', max_length=100)),
                ('hours_arusha_park', models.CharField(default=0, help_text=b'Put The hours spent at arusha national park for this plan', max_length=100)),
                ('days_lake_manyara', models.CharField(default=0, help_text=b'Put The number of days at lake manyara national park for this plan', max_length=100)),
                ('hours_lake_manyara', models.CharField(default=0, help_text=b'Put The hours spent at lake manyara national park for this plan', max_length=100)),
                ('days_lake_eyasi', models.CharField(default=0, help_text=b'Put The number of days at lake eyasi national park for this plan', max_length=100)),
                ('hours_lake_eyasi', models.CharField(default=0, help_text=b'Put The hours spent at lake eyasi national park for this plan', max_length=100)),
                ('days_serengeti', models.CharField(default=0, help_text=b'Put The number of days at serengeti national park for this plan', max_length=100)),
                ('hours_serengeti', models.CharField(default=0, help_text=b'Put The hours spent at serengeti national park for this plan', max_length=100)),
                ('days_ngorongoro', models.CharField(default=0, help_text=b'Put The number of days at Ngorongoro Crater national park for this plan', max_length=100)),
                ('hours_ngorongoro', models.CharField(default=0, help_text=b'Put The hours spent at Ngorongoro Crater national park for this plan', max_length=100)),
                ('days_tarangire', models.CharField(default=0, help_text=b'Put The number of days at Tarangire Crater national park for this plan', max_length=100)),
                ('hours_tarangire', models.CharField(default=0, help_text=b'Put The hours spent at Tarangire Crater national park for this plan', max_length=100)),
                ('days_cultural_vilages', models.CharField(default=0, help_text=b'Put The number of days at Cultural Vilage for this plan', max_length=100)),
                ('hours_cultural_vilages', models.CharField(default=0, help_text=b'Put The hours spent at Cultural Vilage for this plan', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_1_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_2_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_3_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_4_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_5_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_6_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_7_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_8_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_9_image',
            field=models.FileField(default=b'/activity_images/default.png', upload_to=popoteafrica.models.activity_image_location),
        ),
        migrations.AlterField(
            model_name='bookingsforindividualsafaritrip',
            name='trip_booked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popoteafrica.SafariPlansForTheChart'),
        ),
        migrations.DeleteModel(
            name='SafariIteneary',
        ),
    ]
